version: "3.9"

services:
  web:
    image: web-api:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 5s
    ports:
      - "80:8080"
#     networks:
#       - webnet

# networks:
#   webnet:
#     driver: overlay
