<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>   
        <RootNamespace>monitor_ip_4_tool</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <None Update="appsettings.Development.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>

        <None Update="appsettings.json" Condition="'$(DOTNET_ENVIRONMENT)' == 'Production'">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>

        <None Update="client.ovpn">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>

        <None Update="password.txt">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="*.txt">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\share-library\Shared.csproj" />
    </ItemGroup>

</Project>
